### ISSUE TITLE
rq startup issues

### ISSUE THREAD

**Issue by pameyer** [sbgrid/data-capture-module#13]
fresh vagrant/ansible:

root@localhost log]# tail rq_worker.log
Traceback (most recent call last):
  File "/usr/bin/rq", line 7, in <module>
    from rq.cli import main
  File "/usr/lib/python2.6/site-packages/rq/__init__.py", line 6, in <module>
    from .connections import (Connection, get_current_connection, pop_connection,
  File "/usr/lib/python2.6/site-packages/rq/connections.py", line 7, in <module>
    from redis import StrictRedis
ImportError: cannot import name StrictRedis

###
Initial searches on the error not particularly helpful; initial guess is issues w\ not specifying versions in pip or problem with the init script.

**Comment by pameyer** [comment]
Not python redis/rq versions (2.10.5 , 0.6.0 ).

Turned out to be `python-redis` getting installed by yum; because I told ansible to do that for reasons that escape me at the moment.
